import Head from "next/head";

import { Partytown } from "@builder.io/partytown/react";

const HeadLayout = () => {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <Partytown debug={true} forward={["dataLayer.push"]} />
      {/* <!-- Google Tag Manager --> */}
      <script
        type="text/partytown"
        dangerouslySetInnerHTML={{
          __html: `!function(){function t(){var t,e,n,a;t=window,e=document,n="script",t[a="dataLayer"]=t[a]||[],t[a].push({"gtm.start":(new Date).getTime(),event:"gtm.js"}),a=e.getElementsByTagName(n)[0],(n=e.createElement(n)).async=!0,n.src="https://www.googletagmanager.com/gtm.js?id=GTM-5D3JJZT",a.parentNode.insertBefore(n,a)}function e(){setTimeout(t,0)}window.addEventListener?window.addEventListener("load",e,!1):window.attachEvent&&window.attachEvent("onload",e)}();`,
        }}
      />
      {/* <!-- End Google Tag Manager --> */}
    </Head>
  );
};

export default HeadLayout;
